name: test
inputs:
  test:
    description: test defaults
    default: 2

runs:
  using: composite
  steps:
  - name: test
    shell: bash
    env:
      test: ${{ inputs.test }}
    run: |
      echo "test: [$test]" | tee -a "$GITHUB_STEP_SUMMARY"
